defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "archive"
    values:
      layout: "issue"
  -
    scope:
      path: "api"
    values:
      layout: "basic"
